language: node_js
node_js:
  - "7"

before_script:
  - npm install codecov -g
after_success:
  - npm run codecov
  - codecov
deploy:
  provider: npm
  email: "lffate@gmail.com"
  api_key: "${API_TOKEN}"
  on:
    branch: production

notifications:
  email:
    recipients:
    - lffate@gmail.com
    on_success: change
    on_failure: always
